### ISSUE TITLE
Access deep nested store value

### ISSUE THREAD

**Issue by edilsalvador** [Spyna/react-context-hook#1]
Hi, I'm trying to access a specific value in a nested store. But instead of getting the initial value stored in my `initialState` I am getting the default value even though the store is already persisted.

I also tried to set a value but it was being stored
in `userDataStore.status` not in `userDataStore: { status: 'here' }`

Is this the expected behavior? If yes, is there a way to access a specific value without subscribing to the whole object? Thank you!

Here's a sample code:
```
const initialState = {
  userDataStore: {
    status: 'LOGGED_OUT'
  },
};

function App() {
  const store = useStoreState();
  const userStatus = useStoreValue('userDataStore.status', 'NONE');

  console.log({ store, userStatus });

  return (
    <View>
      <Text>{userStatus}</Text>
    </View>
  );
}

export default withStore(App, initialState);
```

![Screenshot from 2019-12-01 22-20-06](https://user-images.githubusercontent.com/17653666/69915336-c7e4f480-1488-11ea-9595-5ceab1727d80.png)

**Comment by Spyna** [comment]
Hi, 
yes, this is the expected behavior. 
An easy solution could be using the hook with the destructuring operator, to access just the nested property. For example:

```JS
const {status} = useStoreValue('userDataStore', {status : 'NONE'});
```
Wich is just the short version for 

```JS
const userDataStore = useStoreValue('userDataStore', {status : 'NONE'});
const {status} = useStoreValue;
```
An important thing to notice is that the **default value** must be the whole Object `userDataStore`.

In the future, I could add an hook like `useNestedProperty('userDataStore', 'status')` or `useNestedProperty('userDataStore.status')`, however the value of this hook will update when the whole object changes, and not only the nested property. 

Please let me know if this helped you.

**Comment by edilsalvador** [comment]
Hi @Spyna, I tried your solution and so far so good :ok_hand:
I recently finished building our web app using this library and will now use it to build a react-native app.
