### ISSUE TITLE
store.set('user') does not trigger re-render without useStore('user')

### ISSUE THREAD

**Issue by dtp5** [Spyna/react-context-hook#30]
`store.set('user')` does not trigger a re-render unless some component explicitly invokes `useStore('user')`. This could occur in a helper file where `'user'` is only read from `store.getState()` and set with `store.set('user')`, as opposed to using `const [user, setUser] = useStore('user')` in a component. The issue is resolved when adding `useStore('user')` unassigned in a parent component.

Is this intended behavior?

**Comment by Spyna** [comment]
Hi, 
thank you for reaching out.
I'm not sure to have fully understood the situation, could you please provide an example of this issue? 

However, 
yes, this is the expected behavior because you want components to re-render only if they use the value in the store. 
`store.getState` is not a react hook, so it doesn't trigger any re-render. 

You could place `useStore('user')` right in the component that needs the value of the *user*. 
There are many hooks you can use, not just `useStore`. For example, if you just need to read the value in the store, without editing it, you can use `useStoreValue` https://spyna.github.io/react-context-hook/docs/#usestorevalue

**Comment by dtp5** [comment]
`useStoreValue` sounds like the right approach. Thanks!
